### ISSUE TITLE
Error Generated Upon Running The Script

### ISSUE THREAD

**Issue by bwpbruce** [khaouitiabdelhakim/Gmail-Creation-Automation-Python#8]
The following error occurs upon running the script:

bwpbruce@DESKTOP-5O4I671:~/Gmail-Creation-Automation-Python$ python3 gmail_automation.py
Traceback (most recent call last):
  File "/home/bwpbruce/Gmail-Creation-Automation-Python/gmail_automation.py", line 13, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

**Comment by Official-CalcOS** [comment]
Mate... please read the error and look yourself rather than posting here immediately. A quick google would solve this for you.
Enter the following in a terminal or a CMD Prompt, it should fix the issue. 
pip install Unidecode

What are you doing with all the Gmail accounts anyhow if I may ask?

**Comment by bwpbruce** [comment]
Thanks, sorry. I tried to find a solution online. I struggled greatly to even get to this point. I had to figure out a hundred previous manually with no help. Your instructions were not as clear as you think. In terms of what I plan to do with the gmail accounts, it's work-related.

**Comment by bwpbruce** [comment]
Encountering further issues:
Traceback (most recent call last):
  File "/home/bwpbruce/Gmail-Creation-Automation-Python/gmail_automation.py", line 21, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/home/bwpbruce/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/bwpbruce/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/bwpbruce/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 105, in start
    self.assert_process_still_running()
  File "/home/bwpbruce/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 118, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/bwpbruce/.cache/selenium/chromedriver/linux64/129.0.6668.70/chromedriver unexpectedly exited. Status code was: 127

**Comment by Official-CalcOS** [comment]
Sorry for being blunt before, Python debugging can be extremely confusing.

How many accounts do you need to make? 
Do they need to have 2FA enabled or a mobile number attached?
Do they need a recovery email?

I'll see if I can find another way for you that's simpler and easier :)

**Comment by bwpbruce** [comment]
1. Multiple, 2. Yes, 3. Yes
